# Generated by Django 2.0.3 on 2018-07-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptrans', '0011_auto_20180728_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_added',
        ),
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
