# Generated by Django 2.1 on 2018-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptrans', '0013_transactiondetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='transaction',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='product',
            name='creditor_name',
            field=models.CharField(default='No creditor', max_length=20000),
        ),
        migrations.DeleteModel(
            name='TransactionDetail',
        ),
    ]
