# Generated by Django 2.1 on 2018-12-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptrans', '0014_auto_20181209_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creditor_name',
            field=models.CharField(default='No creditor', max_length=20000, null=True),
        ),
    ]
