# Generated by Django 2.1 on 2018-12-09 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptrans', '0019_auto_20181209_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singledaytransaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
