# Generated by Django 2.1 on 2018-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptrans', '0020_auto_20181209_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singledaytransaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
