# Generated by Django 2.1 on 2018-12-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptrans', '0021_auto_20181209_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singledaytransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
